- name: Install MongoDB component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: Install MongoDB
    ansible.builtin.yum:  # this is the module to install mongodb
      name: mongodb-org
      state: installed
      